/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ApiResponse {
    /**
     * code of result
     */
    retCode?: number;
    /**
     * 
     */
    type?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    status?: ApiResponse.StatusEnum;
}
export namespace ApiResponse {
    export type StatusEnum = 1 | 2;
    export const StatusEnum = {
        NUMBER_1: 1 as StatusEnum,
        NUMBER_2: 2 as StatusEnum
    }
}
