/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseThingcategory {
    /**
     *  合作方式：0=买断
     */
    id?: number;
    /**
     *  分类名称
     */
    title?: string;
    /**
     *  类别编码
     */
    categoryCode?: string;
    /**
     *  分类英文标题
     */
    engTitle?: string;
    /**
     *  顶层Id
     */
    tid?: number;
    /**
     *  父Id
     */
    fid?: number;
    /**
     *  工作量单位
     */
    workUnitId?: number;
    /**
     *  0=正常，1=禁用
     */
    status?: number;
    /**
     *  是否发布0=已发布，1=未发布
     */
    isPublish?: number;
    /**
     *  0=未删除 1=已删除 2=删除未发布
     */
    isDel?: number;
    /**
     *  排序，从小到大
     */
    sort?: number;
    /**
     *  分类类型。默认0为美术，1为音频
     */
    categoryType?: number;
    /**
     *  分类说明
     */
    content?: string;
    /**
     *  合作方式：0=买断
     */
    cooperationType?: number;
    /**
     *  大分类
     */
    bigCategory?: number;
    /**
     * 
     */
    code?: string;
    /**
     *  分类英文Code
     */
    engCode?: string;
    /**
     *  招募时是否显示0:隐藏,1:显示,
     */
    recuritIsShow?: number;
}
