/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseCompany {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    supplierId?: number;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    registerDate?: string;
    /**
     * 
     */
    registeredCapital?: number;
    /**
     * 
     */
    memberCount?: number;
    /**
     * 
     */
    cityId?: number;
    /**
     * 
     */
    address?: string;
    /**
     * 
     */
    businessLicenseRegistrationNumber?: string;
    /**
     * 
     */
    organizationCodeNumber?: string;
    /**
     * 
     */
    taxRegistrationNumber?: string;
    /**
     * 
     */
    corporateLegalPersonName?: string;
    /**
     * 
     */
    corporateLegalPersonPhone?: string;
    /**
     * 
     */
    corporateLegalPersonMail?: string;
    /**
     * 
     */
    headOfTheCompanyName?: string;
    /**
     * 
     */
    headOfTheCompanyPhone?: string;
    /**
     * 
     */
    headOfTheCompanyMail?: string;
    /**
     * 
     */
    headOfTheCompanyQq?: string;
    /**
     * 
     */
    businessLeaderName?: string;
    /**
     * 
     */
    businessLeaderPhone?: string;
    /**
     * 
     */
    businessLeaderMail?: string;
    /**
     * 
     */
    businessLeaderQq?: string;
    /**
     * 
     */
    makingThePersonInChargeName?: string;
    /**
     * 
     */
    makingThePersonInChargePhone?: string;
    /**
     * 
     */
    makingThePersonInChargeMail?: string;
    /**
     * 
     */
    makingThePersonInChargeQq?: string;
    /**
     * 
     */
    attachmentIdForBusinessLicenseRegistration?: number;
    /**
     * 
     */
    attachmentIdForOrganizationCode?: number;
    /**
     * 
     */
    attachmentIdForTaxRegistration?: number;
    /**
     * 
     */
    attachmentIdForBankAccountOpeningCertificate?: number;
    /**
     * 
     */
    attachmentIdForIntroduction?: number;
}
