/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseWork {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    supplier_id?: number;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    category_id?: number;
    /**
     * 
     */
    style_id?: number;
    /**
     * 
     */
    thumbnail_attachment_id?: number;
    /**
     * 
     */
    work_attachment_id?: number;
}
