/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseUploadFile {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    hash_name?: string;
    /**
     * 
     */
    file_name?: string;
    /**
     * 
     */
    file_size?: string;
    /**
     * 
     */
    file_type?: string;
    /**
     * 
     */
    file_path?: string;
    /**
     * 
     */
    creator?: string;
    /**
     * 
     */
    create_time?: string;
}
