/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseThingcategory {
    /**
     *  合作方式：0=买断
     */
    Id?: number;
    /**
     *  分类名称
     */
    Title?: string;
    /**
     *  类别编码
     */
    CategoryCode?: string;
    /**
     *  分类英文标题
     */
    EngTitle?: string;
    /**
     *  顶层Id
     */
    Tid?: number;
    /**
     *  父Id
     */
    Fid?: number;
    /**
     *  工作量单位
     */
    WorkUnitId?: number;
    /**
     *  0=正常，1=禁用
     */
    Status?: number;
    /**
     *  是否发布0=已发布，1=未发布
     */
    IsPublish?: number;
    /**
     *  0=未删除 1=已删除 2=删除未发布
     */
    IsDel?: number;
    /**
     *  排序，从小到大
     */
    Sort?: number;
    /**
     *  分类类型。默认0为美术，1为音频
     */
    CategoryType?: number;
    /**
     *  分类说明
     */
    Content?: string;
    /**
     *  合作方式：0=买断
     */
    CooperationType?: number;
    /**
     *  大分类
     */
    BigCategory?: number;
    /**
     * 
     */
    Code?: string;
    /**
     *  分类英文Code
     */
    EngCode?: string;
    /**
     *  招募时是否显示0:隐藏,1:显示,
     */
    RecuritIsShow?: number;
}
