/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseCategoryHasWorkloadUnit } from './baseCategoryHasWorkloadUnit';


export interface CategoryHasWorkloadUnit {
    /**
     * 
     */
    category_id?: number;
    /**
     * 
     */
    workload_unit_id?: number;
}
