/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseCompany } from './baseCompany';


export interface Company {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    supplier_id?: number;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    register_date?: string;
    /**
     * 
     */
    registered_capital?: number;
    /**
     * 
     */
    member_count?: number;
    /**
     * 
     */
    city_id?: number;
    /**
     * 
     */
    address?: string;
    /**
     * 
     */
    business_license_registration_number?: string;
    /**
     * 
     */
    organization_code_number?: string;
    /**
     * 
     */
    tax_registration_number?: string;
    /**
     * 
     */
    corporate_legal_person_name?: string;
    /**
     * 
     */
    corporate_legal_person_phone?: string;
    /**
     * 
     */
    corporate_legal_person_mail?: string;
    /**
     * 
     */
    person_in_charge_name?: string;
    /**
     * 
     */
    person_in_charge_phone?: string;
    /**
     * 
     */
    person_in_charge_mail?: string;
    /**
     * 
     */
    person_in_charge_qq?: string;
    /**
     * 
     */
    business_leader_name?: string;
    /**
     * 
     */
    business_leader_phone?: string;
    /**
     * 
     */
    business_leader_mail?: string;
    /**
     * 
     */
    business_leader_qq?: string;
    /**
     * 
     */
    producer_name?: string;
    /**
     * 
     */
    producer_phone?: string;
    /**
     * 
     */
    producer_mail?: string;
    /**
     * 
     */
    producer_qq?: string;
    /**
     * 
     */
    attachment_id_for_business_license_registration?: number;
    /**
     * 
     */
    attachment_id_for_organization_code?: number;
    /**
     * 
     */
    attachment_id_for_tax_registration?: number;
    /**
     * 
     */
    attachment_id_for_bank_account_opening_certificate?: number;
    /**
     * 
     */
    attachment_id_for_introduction?: number;
}
