/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pager } from './pager';
import { User } from './user';


export interface InlineResponse2002 {
    ret_code?: number;
    list?: Array<User>;
    pager?: Pager;
    errors?: any;
}
