/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pager } from './pager';
import { WorkflowInstance } from './workflowInstance';


export interface InlineResponse2005 {
    ret_code?: number;
    list?: Array<any>;
    pager?: Pager;
    errors?: any;
    data?: Array<WorkflowInstance>;
}
