/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkflowInstance } from './workflowInstance';


export interface InlineResponse2008 {
    ret_code?: number;
    data?: WorkflowInstance;
    errors?: any;
}
