/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasePerson } from './basePerson';


export interface Person {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    supplier_id?: number;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    identity_no?: string;
    /**
     * 
     */
    career_begin_time?: string;
    /**
     * 
     */
    city_id?: number;
    /**
     * 
     */
    address?: string;
    /**
     * 
     */
    qq?: string;
    /**
     * 
     */
    phone?: string;
    /**
     * 
     */
    mail?: string;
    /**
     * 
     */
    attachment_id?: number;
}
