/**
 * 接口文档
 * Version: __0.0.1__
 *
 * OpenAPI spec version: 0.0.1
 * Contact: binghuiluo@tencent.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseWorkflowTask } from './baseWorkflowTask';


export interface WorkflowTask {
    /**
     * 
     */
    id?: number;
    /**
     * 
     */
    last_node_id?: number;
    /**
     * 
     */
    instance_id?: number;
    /**
     * 
     */
    node_id?: number;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    type?: string;
    /**
     * 
     */
    assignee?: string;
    /**
     * 
     */
    complete_user?: string;
    /**
     * 
     */
    create_time?: string;
    /**
     * 
     */
    complete_time?: string;
    /**
     * 
     */
    data?: string;
    /**
     * 
     */
    extra_data?: string;
}
